### ISSUE TITLE
hand_finder cannot work with empty mapping

### ISSUE THREAD

**Issue by guihomework** [shadow-robot/sr_core#34]
The current hand finder is designed to store mapping (naming) of the hands in a dictionary with serial_id as key, and joint_prefix uses mapping as key. 
This is problematic if the mapping is empty.

Also, there are some mix-up between mapping and joint_prefix, sometimes joint_prefix is generated from mapping + "_"

Finally config folder name should be separate from mapping.

I created a branch in my fork (https://github.com/ubi-agni/sr_core/tree/F_handfinder_namespace) , that adds a config_dir, relies on serial_id as the key (as this is never empty and always unique), handles empty prefix, fixes the mix-up and adds tests.

If you like the suggested solution, I can adapt part of the other software (sr_edc_launch and friends) to work with the hand_finder. Theoretically the other software only using prefix and mapping and no config_dir, and should not need modification when calling the hand finder.

**Comment by guihomework** [comment]
I summarize the ideas we discussed on the phone here :
- do as minimal changes as possible to `handfinder`
- do not introduce a new parameter for `config_dir` but rely on `serial_id` if mapping is empty.
- launch file can use `serial_id` for folder finding. 
  This means, one needs to add a symbolic link called `rh` to the `serial_id` the customer has in the `sr_ethercat_hand_config` and similar for `lh`
- GUI tools will then display `hand_id` if any or `serial_id` if no mapping was found.
- `hand_finder` should store the dictionary with `serial_id` all the time. One should verify if this is not a problem.

**Comment by VahidAminZ** [comment]
@guihomework regarding your last point, a better compromise can be hand_finder return dictionary with hand_id if any and hand_serial if no hand_id is present.

**Comment by guihomework** [comment]
@VahidAminZ I can do that, but I think this does not simplify understanding. I think the hand_id for human readibility, at lower level the hand serial is used anyway to distinguish the hands. In a GUI, it obviously make sense to use the human readable hand_id, the software should care about the finding which hand/joints/controllers hand_id refer to via a reverse mapping on serial. 
But I coded for now your solution and also fixed some code to match that solution as it was not the case until now. In the hand_finder.cpp the joints dictionary/map had the joint_prefix as key and joint_list with prefixes as values where it should be hand_id as key.

**Comment by guihomework** [comment]
I did a few commits on a new branch, to fix one of the mentioned problems per commit. All tests even new ones pass, 
I now need to test it on my platform in relation with sr_edc_launch and GUIs, and then I will do a pull request. If you want to have an overlook at the code before, here it is https://github.com/ubi-agni/sr_core/tree/B%2334_emptymapping

**Comment by guihomework** [comment]
Apparently the fixes uncovered another issue. The "waiting for the controller manager" message  https://github.com/shadow-robot/ros_ethercat/blob/indigo-devel/ros_ethercat_model/src/ros_ethercat_model/calibrate_class.py#L31 of the Calibrate parent class of CalibrateWithHand is never displayed. This means there is no waiting for the controller_manager to appear and directly the spawing occurs and then goes in a wait loop for the calibration controllers to be there. In some race conditions it could be possible that the controller manager is not yet available and this ends in a lockup.

It appears that with the fixes in the handfinder, some race conditions are worse and make the calibration lockup as explained above, come more often.

The solution is to initialize the ros node before instantiating the CalibrateWithHand class. Then the message displays and there is no lockup.
It is related to this handfinder somehow, so I add that fix also to the upcoming PR.

**Comment by guihomework** [comment]
Some GUIs do not work now, due to mapping receiving serial when empty. Will investigate

**Comment by guihomework** [comment]
GUIs cannot work nice with current solution, but there is no good solution except fixing https://github.com/shadow-robot/sr-ros-interface-ethercat/issues/56 to make the namespacing consistent and ROS compatible (no namespace in the middle except for joint names prefix) and so on.
