### ISSUE TITLE
[sr_mechanism_controllers] Velocity controller deadband putting effort to zero

### ISSUE THREAD

**Issue by guihomework** [shadow-robot/sr_core#68]
The velocity controller is not working properly. When the target velocity is reached, jerking appears. This is due to the deadband forcing the commanded effort to zero here.

https://github.com/shadow-robot/sr_core/blob/indigo-devel/sr_mechanism_controllers/src/srh_joint_velocity_controller.cpp#L236

The very first time this code was added is here https://github.com/shadow-robot/sr-ros-interface-ethercat/commit/bd251ae982ad6b113a0d2c74d7974b83edc2393d  and the deadband was added to all the controllers but the behaviour when in the deadband should not be identical for a position or a velocity or effort controller.

In vacuum, with no friction, and no external forces, it is true that when a velocity is reached one should stop accelerate, so stop adding efforts to the joint, which would continue at the current velocity. 
In the hand, there is a lot of friction (tendon, air) and external forces (gravity), and the effort on the tendon must be maintained to compensate all the external efforts and then keep the velocity (no acceleration if the motor just compensates the external efforts). 

For this reason, the force should not be put to zero but maintained. However Error in velocity could be set to zero to not further modify the PID internal terms. 

Applying what I suggest works great except when velocity target is zero. Then the PID still might command some effort and the joint moves very little, within the deadband. So there should be a special case if the velocity enters the deadband around a target of zero, to reset the PID and fully stop the movement.

I can provide a PR for that if you agree that this is a bug.

**Comment by toliver** [comment]
@guihomework Your explanation makes sense. It probably is a bug. We are not using the velocity controller, so it hasn't been well tested.

Please provide a PR and we are happy to merge your fix.
